### ISSUE TITLE
Live demo link

### ISSUE THREAD

**Issue by rammazzoti2000** [vzdrizhni/Sample-app#6]
You should put the link to the live demo of the app, I would really like to try it out

**Comment by vzdrizhni** [comment]
I have problems with active storage on heroku, need to fix it first.

**Comment by vzdrizhni** [comment]
https://damp-island-90609.herokuapp.com/ here's the link

**Comment by rammazzoti2000** [comment]
I tried to sign up but it gives me error, signin in with existent user works

**Comment by vzdrizhni** [comment]
mailer doesn't work, and I don't care.

**Comment by rammazzoti2000** [comment]
No problem, I thought you should know the signup is not working
